name: Prevent Lockfile Modifications

on:
  pull_request:
    branches:
      - master

jobs:
  trigger:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger internal checks via ci-public-proxy
        run: echo "Triggering ci-public-proxy for dependency age check"
